version: "3"
services:
  postgres:
    image: postgres:16.1
    user: postgres
    command: -c jit=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: worthefen-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - worthefen-postgres-dev:/var/lib/postgresql/data
volumes:
  worthefen-postgres-dev:
