name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'
    - run: yarn install
    - run: yarn lint
    env:
      CI: true
      SKIP_ENV_VALIDATION: true
